# Generated by Django 4.2.3 on 2023-07-27 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_apply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='recruiter',
            new_name='job',
        ),
    ]
